# Train Test Split

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

## Generate data that we are going to split

In [3]:
a=np.arange(1,101)
print(a)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [4]:
b=np.arange(501,600)
print(b)

[501 502 503 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518
 519 520 521 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536
 537 538 539 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554
 555 556 557 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572
 573 574 575 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590
 591 592 593 594 595 596 597 598 599]


## Split the data

In [7]:
a_train,a_test=train_test_split(a)

In [8]:
a_train.shape,a_test.shape  # Default split is 75% and 25%

((75,), (25,))

We can also adjust split size

In [9]:
a_train,a_test=train_test_split(a,test_size=0.2)
a_train.shape,a_test.shape

((80,), (20,))

The data splitted will be shuffled but we can change that by setting shuffle = false
This is very important in time series dataset where we dont want day to be shuffled

In [13]:
a_train,a_test=train_test_split(a,test_size=0.2)   # With no shuffle
a_train,a_test

(array([37, 25, 21, 97, 39, 18,  3, 91,  9, 80,  4, 77, 96, 32, 44, 27, 81,
        94, 85, 57, 20,  6, 53, 95, 89, 92, 99, 24, 16, 68, 26, 79, 60, 78,
        14, 82, 17, 72, 66, 46, 88,  7, 22, 28, 84, 50, 36, 87,  8, 67, 90,
        51, 61, 15, 13, 42, 56, 55, 31, 29, 49, 63, 41, 71, 11, 62, 10, 45,
        75, 74, 35, 69,  5, 93, 43, 98, 70, 73, 83, 38]),
 array([100,  58,  54,   1,  86,  30,  47,  65,  19,  48,  76,   2,  34,
         64,  59,  40,  33,  52,  23,  12]))

In [12]:
a_train,a_test=train_test_split(a,test_size=0.2,shuffle=False)  #With shuffle
a_train,a_test

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
        52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
        69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80]),
 array([ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
         94,  95,  96,  97,  98,  99, 100]))