# Multiple Linear Regression

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
sns.set()

## Loading the data

In [3]:
data=pd.read_csv("29588240-1.02.Multiple-linear-regression.csv")
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [4]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

## Splitting the data

In [14]:
x=data[["SAT","Rand 1,2,3"]]
y=data["GPA"]

## Creating regression

In [18]:
reg=LinearRegression()

In [26]:
x.shape   # already a 2D array no need to reshape it

(84, 2)

## Training the model

In [20]:
reg.fit(x,y)
reg.get_params(deep=True)

{'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'positive': False}

In [22]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [25]:
reg.intercept_

0.29603261264909486

## R Squared

In [29]:
reg.score(x,y)

0.4066811952814282

## Formula of Adjusted R Squared
### $R^2_{adj}=1-(1-R^2)\frac{n-1}{n-p-1}$
### where n -> no of observation and p -> no of predictors

In [44]:
def adj_r2(x,y):
    r2=reg.score(x,y)
    n=x.shape[0]
    p=x.shape[1]
    return 1-(1-r2)*((n-1)/(n-p-1))
print(adj_r2(x,y))

0.39203134825134


## Detecting which variable is unneeded
## This is also called as Feature Selection

In [34]:
from sklearn.feature_selection import f_regression

In [35]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

## First array -> F value Second array -> P value

In [36]:
p_values=f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [37]:
p_values.round(3)

array([0.   , 0.676])

### P value of rand 1,2,3 is >0.05 so it is not needed

## Creating Summary Table

In [40]:
reg_summary=pd.DataFrame(data=x.columns.values,columns=["Features"])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [42]:
reg_summary["Coefficients"]=reg.coef_
reg_summary["P-value"]=p_values.round(3)
reg_summary

Features  Coefficients  P-value
0         SAT      0.001654    0.000
1  Rand 1,2,3     -0.008270    0.676