# Simple Linear Regression

In [16]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

## Load the Data

In [17]:
data=pd.read_csv("29588160-1.01.Simple-linear-regression.csv")
data.head()

SAT   GPA
0  1714  2.40
1  1664  2.52
2  1760  2.54
3  1685  2.74
4  1693  2.83

## Splitting the data

In [18]:
x=data["SAT"]  #feature
y=data["GPA"]  #target

In [19]:
print(x.shape,y.shape)

(84,) (84,)


## We have to convert 1D to 2D array

In [20]:
x_matrix=x.values.reshape(-1,1)
x_matrix.shape

(84, 1)

## Creating Regression

In [21]:
reg=LinearRegression()

In [22]:
reg.fit(x_matrix,y)

LinearRegression()

## R Squared

In [23]:
reg.score(x_matrix,y)

0.40600391479679765

## Coefficients

In [24]:
reg.coef_

array([0.00165569])

## Intercept

In [25]:
reg.intercept_

0.27504029966028076

In [26]:
test=np.array([1740,1890,1700])
test=test.reshape(-1,1)
reg.predict(test)

array([3.15593751, 3.40429071, 3.08970998])

In [27]:
df=pd.DataFrame(data=[1740,1890,1700],columns=["SAT"])
df

SAT
0  1740
1  1890
2  1700

In [28]:
reg.predict(df)

C:\Users\Magesh\anaconda3\lib\site-packages\sklearn\base.py:432: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([3.15593751, 3.40429071, 3.08970998])

In [29]:
df["Predicted GPA"]=reg.predict(df)
df

C:\Users\Magesh\anaconda3\lib\site-packages\sklearn\base.py:432: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


SAT  Predicted GPA
0  1740       3.155938
1  1890       3.404291
2  1700       3.089710

In [30]:
reg.get_params(deep=True)

{'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'positive': False}