# Real Estate

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import f_regression

## Loading the data

In [2]:
data=pd.read_csv("29588430-real-estate-price-size-year.csv")
data.head()

price     size  year
0  234314.144   643.09  2015
1  228581.528   656.22  2009
2  281626.336   487.29  2018
3  401255.608  1504.75  2015
4  458674.256  1275.46  2009

## Splitting the data

In [3]:
y=data["price"]
x=data[["size","year"]]

## Standardize the data

In [5]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x,y)

StandardScaler()

In [7]:
x_scaled=scaler.transform(x)
x_scaled

array([[-0.70816415,  0.51006137],
       [-0.66387316, -0.76509206],
       [-1.23371919,  1.14763808],
       [ 2.19844528,  0.51006137],
       [ 1.42498884, -0.76509206],
       [-0.937209  , -1.40266877],
       [-0.95171405,  0.51006137],
       [-0.78328682, -1.40266877],
       [-0.57603328,  1.14763808],
       [-0.53467702, -0.76509206],
       [ 0.69939906, -0.76509206],
       [ 3.33780001, -0.76509206],
       [-0.53467702,  0.51006137],
       [ 0.52699137,  1.14763808],
       [ 1.51100715, -1.40266877],
       [ 1.77668568, -1.40266877],
       [-0.54810263,  1.14763808],
       [-0.77276222, -1.40266877],
       [-0.58004747, -1.40266877],
       [ 0.58943055,  1.14763808],
       [-0.78365788,  0.51006137],
       [-1.02322731,  0.51006137],
       [ 1.19557293,  0.51006137],
       [-1.12884431,  0.51006137],
       [-1.10378093, -0.76509206],
       [ 0.84424715,  1.14763808],
       [-0.95171405,  1.14763808],
       [ 1.62279723,  0.51006137],
       [-0.58004747,

## Create Regression

In [8]:
reg=LinearRegression()
reg.fit(x_scaled,y)

LinearRegression()

In [9]:
reg.intercept_

292289.4701599997

In [10]:
reg.coef_

array([67501.57614152, 13724.39708231])

In [11]:
reg.score(x_scaled,y)

0.7764803683276793

## Creating summary table

In [14]:
p_value=f_regression(x_scaled,y)[1]
p_value=p_value.round(3)
p_value

array([0.   , 0.357])

## Summmary Table

In [20]:
reg_summary=pd.DataFrame(data=["Size","Year"],columns=["Features"])
reg_summary["Weights"]=reg.coef_[0],reg.coef_[1]
reg_summary["p value"]=p_value[0],p_value[1]
reg_summary

Features       Weights  p value
0     Size  67501.576142    0.000
1     Year  13724.397082    0.357

## Making Prediction
that data also needs to be standardized

In [24]:
new_data=[[750,2009]]
new_data_scaled=scaler.transform((new_data))
new_data_scaled

C:\Users\Magesh\anaconda3\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-0.34752816, -0.76509206]])

In [25]:
reg.predict(new_data_scaled)

array([258330.34465995])