# Feature selection through Standarisation

In [58]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import f_regression

## Loading the data

In [59]:
data=pd.read_csv("29588388-1.02.Multiple-linear-regression.csv")
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [60]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

## Splitting the data

In [61]:
y=data["GPA"]
x=data[["SAT","Rand 1,2,3"]]

## Standardisation

we will use StandardScaler() from sklearn and use the scaled feature to create regression

In [62]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [63]:
scaler.fit(x)
scaler.get_params(deep=True)

{'copy': True, 'with_mean': True, 'with_std': True}

In [64]:
scaler.mean_

array([1845.27380952,    2.05952381])

In [65]:
x_scaled=scaler.transform(x)

In [66]:
print(x_scaled)

[[-1.26338288 -1.24637147]
 [-1.74458431  1.10632974]
 [-0.82067757  1.10632974]
 [-1.54247971  1.10632974]
 [-1.46548748 -0.07002087]
 [-1.68684014 -1.24637147]
 [-0.78218146 -0.07002087]
 [-0.78218146 -1.24637147]
 [-0.51270866 -0.07002087]
 [ 0.04548499  1.10632974]
 [-1.06127829  1.10632974]
 [-0.67631715 -0.07002087]
 [-1.06127829 -1.24637147]
 [-1.28263094  1.10632974]
 [-0.6955652  -0.07002087]
 [ 0.25721362 -0.07002087]
 [-0.86879772  1.10632974]
 [-1.64834403 -0.07002087]
 [-0.03150724  1.10632974]
 [-0.57045283  1.10632974]
 [-0.81105355  1.10632974]
 [-1.18639066  1.10632974]
 [-1.75420834  1.10632974]
 [-1.52323165 -1.24637147]
 [ 1.23886453 -1.24637147]
 [-0.18549169 -1.24637147]
 [-0.5608288  -1.24637147]
 [-0.23361183  1.10632974]
 [ 1.68156984 -1.24637147]
 [-0.4934606  -0.07002087]
 [-0.73406132 -1.24637147]
 [ 0.85390339 -1.24637147]
 [-0.67631715 -1.24637147]
 [ 0.09360513  1.10632974]
 [ 0.33420585 -0.07002087]
 [ 0.03586096 -0.07002087]
 [-0.35872421  1.10632974]
 

## Regression with Scaled Feature

In [67]:
reg=LinearRegression()
reg.fit(x_scaled,y)

LinearRegression()

In [68]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [69]:
reg.score(x_scaled,y)

0.4066811952814283

In [70]:
reg.intercept_

3.330238095238095

## Creating Summary Table

In [71]:
reg_summary=pd.DataFrame(data=["Bias","SAT","Rand 1,2,3"],columns=["Features"])
reg_summary["Weight"]=reg.intercept_,reg.coef_[0],reg.coef_[1]
reg_summary

Features    Weight
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

Weight -> ML term of 'coefficient'
Bias -> ML term of 'intercept'

## Making prediction after standardisation

The new data for prediction also need to be standardized

In [72]:
new_data=pd.DataFrame(data=[[1700,2],[1800,1]],columns=["SAT","Rand 1,2,3"])
new_data

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [73]:
reg.predict(new_data)

C:\Users\Magesh\anaconda3\lib\site-packages\sklearn\base.py:432: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([295.39979563, 312.58821497])

we also needs to standardize the new data

In [74]:
new_data_scaled=scaler.transform(new_data)
new_data_scaled

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [75]:
reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])

This is prediction of the scaled data

### What is we remove Rand 1,2,3

In [78]:
reg_simple=LinearRegression()
x_simple_matrix=x_scaled[:,0].reshape(-1,1)
reg_simple.fit(x_simple_matrix,y)

LinearRegression()

In [84]:
reg_simple.predict(new_data_scaled[:,0].reshape(-1,1))

array([3.08970998, 3.25527879])