# Numpy Array

In [164]:
import numpy as np

In [165]:
array=np.array(range(5))
array

array([0, 1, 2, 3, 4])

In [166]:
array_2d=np.array([range(5),range(5)])
array_2d

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [167]:
array_2d.shape

(2, 5)

In [168]:
array_2d.size

10

In [169]:
array_2d.dtype

dtype('int32')

In [170]:
array_2d.T   ## Transpose

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

## Ways to create arrays

In [171]:
array1=np.ones((5,3),dtype="float")
array1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [172]:
arrayzero=np.zeros((5,3),dtype="int")
arrayzero

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [173]:
array_range=np.arange(1,10,2)
array_range

array([1, 3, 5, 7, 9])

In [174]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [175]:
np.linspace(0,100,5).reshape(1,5)

array([[  0.,  25.,  50.,  75., 100.]])

In [176]:
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [177]:
np.linspace(0,100,10)  ## We need extra or including zero

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [178]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### Random number

In [179]:
from numpy.random import default_rng

In [180]:
rng=default_rng(42)

In [181]:
randoms=rng.random(10)
randoms

array([0.77395605, 0.43887844, 0.85859792, 0.69736803, 0.09417735,
       0.97562235, 0.7611397 , 0.78606431, 0.12811363, 0.45038594])

we can create normal distribution

In [182]:
mean,std=6,1
random=rng.normal(mean,std,size=10)
random

array([6.87939797, 6.77779194, 6.0660307 , 7.12724121, 6.46750934,
       5.14070754, 6.36875078, 5.0411174 , 6.8784503 , 5.95007409])

In [183]:
print(rng.integers(0,10,100))

[1 7 7 3 0 9 4 8 6 7 7 1 3 4 4 0 5 1 7 6 9 7 3 9 4 3 9 3 0 4 7 1 4 1 6 4 3
 2 5 6 9 4 1 8 6 7 0 3 7 8 4 8 8 3 8 2 2 6 6 1 8 1 8 0 7 7 7 6 4 7 2 7 5 4
 5 5 0 1 2 1 4 6 6 4 8 5 0 7 5 6 5 5 0 5 7 3 6 0 3 4]


In [184]:
np.arange(10,101,10).reshape(5,2)

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [185]:
test_rnd=default_rng(2022)
rand=test_rnd.random(9)
rand.reshape(3,3)


array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

### Slicing

In [186]:
array=np.arange(12)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [187]:
array[1]

1

In [188]:
array[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [189]:
array[::2]

array([ 0,  2,  4,  6,  8, 10])

In [190]:
array=array.reshape(4,3)

In [191]:
array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [192]:
array[1:,1:]

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

In [193]:
array[:,:2]

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10]])

In [194]:
gener=default_rng(42)
array1=gener.integers(0,100,10)
array1

array([ 8, 77, 65, 43, 43, 85,  8, 69, 20,  9], dtype=int64)

In [195]:
array1-20

array([-12,  57,  45,  23,  23,  65, -12,  49,   0, -11], dtype=int64)

In [196]:
array1/2

array([ 4. , 38.5, 32.5, 21.5, 21.5, 42.5,  4. , 34.5, 10. ,  4.5])

In [197]:
arraylist=list(array1)
arrr=[x+2 for x in arraylist]
arrr

[10, 79, 67, 45, 45, 87, 10, 71, 22, 11]

In [198]:
rand=gener.random(9).reshape(3,3)
rand

array([[0.97562235, 0.7611397 , 0.78606431],
       [0.12811363, 0.45038594, 0.37079802],
       [0.92676499, 0.64386512, 0.82276161]])

In [199]:
(rand[:2,:].reshape(6))+10

array([10.97562235, 10.7611397 , 10.78606431, 10.12811363, 10.45038594,
       10.37079802])

In [200]:
sales=np.array([[0,10,-2,3],[10,78,2,-3]],dtype="int")

In [201]:
sales>0

array([[False,  True, False,  True],
       [ True,  True,  True, False]])

In [202]:
sales[sales>0]

array([10,  3, 10, 78,  2])

## Where

In [203]:
inverntory=np.array([10,0,20,0,1])

In [204]:
np.where(inverntory>0,"Stock","Out of stock")

array(['Stock', 'Out of stock', 'Stock', 'Out of stock', 'Stock'],
      dtype='<U12')

In [205]:
myarr=np.arange(0,10)

In [206]:
np.where(myarr%2==0,"Even","Odd")

array(['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd'], dtype='<U4')

In [207]:
myarr.sum()

45

In [208]:
myarr.mean()

4.5

In [209]:
myarr.max()

9

In [210]:
arr=np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [211]:
arr[:,:2].sum(axis=1)

array([ 1,  7, 13])

In [212]:
arr.sum(axis=1)

array([ 3, 12, 21])

In [213]:
np.median(arr)

4.0

In [214]:
np.percentile(arr,99)

7.92

## Assignment

In [215]:
import pandas as pd

In [216]:
df=pd.read_csv("retail_2016_2017.csv")
df.head()

id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1   BABY CARE    0.0            0
2  1945946  2016-01-01          1      BEAUTY    0.0            0
3  1945947  2016-01-01          1   BEVERAGES    0.0            0
4  1945948  2016-01-01          1       BOOKS    0.0            0

In [217]:
family_array=np.array(df["family"])
sales_array=np.array(df["sales"])

In [218]:
sales_array[family_array=="PRODUCE"].size

31968

In [219]:
product_sales=[sales_array[family_array=="PRODUCE"]]
product_sales

[array([   0.   ,    0.   ,    0.   , ..., 5113.961, 3939.392, 2419.729])]