# Numpy Array

In [1]:
import numpy as np

In [2]:
array=np.array(range(5))
array

array([0, 1, 2, 3, 4])

In [3]:
array_2d=np.array([range(5),range(5)])
array_2d

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [4]:
array_2d.shape

(2, 5)

In [5]:
array_2d.size

10

In [6]:
array_2d.dtype

dtype('int32')

In [7]:
array_2d.T   ## Transpose

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

## Ways to create arrays

In [8]:
array1=np.ones((5,3),dtype="float")
array1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
arrayzero=np.zeros((5,3),dtype="int")
arrayzero

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [10]:
array_range=np.arange(1,10,2)
array_range

array([1, 3, 5, 7, 9])

In [11]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [12]:
np.linspace(0,100,5).reshape(1,5)

array([[  0.,  25.,  50.,  75., 100.]])

In [13]:
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
np.linspace(0,100,10)  ## We need extra or including zero

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [15]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### Random number

In [17]:
from numpy.random import default_rng

In [18]:
rng=default_rng(42)

In [20]:
randoms=rng.random(10)
randoms

array([0.77395605, 0.43887844, 0.85859792, 0.69736803, 0.09417735,
       0.97562235, 0.7611397 , 0.78606431, 0.12811363, 0.45038594])

we can create normal distribution

In [21]:
mean,std=6,1
random=rng.normal(mean,std,size=10)
random

array([6.87939797, 6.77779194, 6.0660307 , 7.12724121, 6.46750934,
       5.14070754, 6.36875078, 5.0411174 , 6.8784503 , 5.95007409])

In [24]:
print(rng.integers(0,10,100))

[9 2 2 4 9 8 0 2 8 0 8 2 9 2 4 6 1 5 5 7 9 6 4 4 4 8 3 1 3 0 1 0 7 7 6 4 7
 1 9 5 9 1 4 6 4 4 1 3 2 3 6 6 6 3 9 0 3 1 3 9 3 9 4 6 4 2 7 9 2 7 2 7 7 4
 7 2 0 0 4 9 1 4 7 2 7 3 8 5 5 1 4 8 0 7 4 7 6 4 3 6]


In [26]:
np.arange(10,101,10).reshape(5,2)

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [29]:
test_rnd=default_rng(2022)
rand=test_rnd.random(9)
rand.reshape(3,3)


array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

### Slicing

In [30]:
array=np.arange(12)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
array[1]

1

In [32]:
array[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
array[::2]

array([ 0,  2,  4,  6,  8, 10])

In [34]:
array=array.reshape(4,3)

In [35]:
array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
array[1:,1:]

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

In [40]:
array[:,:2]

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10]])